Dev
KostyaDemens/currencyExchange pull request #1
Opened 2024-02-03 16:54 UTC by KostyaDemens

2024-02-05 19:02 UTC, TurboGoose requested changes
Что еще улучшить:
- Не удалил index.jsp, который тут не нужен.
- Папку .idea лучше добавить в gitignore. Это правило не всегда работает - в тяжелых проектах, которые требуют особых правил запуска идеи, эту папку с конфигами оставляют, но если случай стандартный, то лучше ее игнорить.
- В каждом контроллере каждый раз делается конвертация в json и установка content-type - лучше вынести это в базовый класс и/или фильтр.
- Не выставляешь заголовок character encoding.
- Не везде соблюдено форматирование (в intellij idea есть шорткат, который двумя кнопками форматирует файл - поищи, полезная штука).
- Использование float для операций с суммами. Его нельзя использовать при работе с денежными суммами в связи с тонкостями арифметики чисел с плавающей точкой в java. Попробуй в java выполнить `0.1 + 0.2` и посмотри, что получится.
- Вместо json ответов в случае ошибок возвращается tomcat'овская html страничка.

- Не единообразная обработка ошибок:
```java
if (path.isEmpty()) {  
    resp.sendError(400);  
} else if (jsonObject.isEmpty()) {  
    resp.sendError(404);  
} else {  
    PrintWriter out = resp.getWriter();  
    out.println(jsonObject);  
}
```
или
```java
if (code == null || fullName == null || sign == null) {  
	resp.sendError(400, "Отсутствует нужное поле формы");  
	return;
} else if (currencyDao.isCodeExists(code)) {  
	resp.sendError(409, "Валюта с таким кодом уже существует");  
	return;
}
```
Также тут видно, что не везде выводишь информацию об ошибках

Также на ближайшую итерацию:
- Просмотреть чеклист для самопроверки на страничке проекта в роадмапе
- Переписать с postgres на SQLite
- Добавить readme с описанием проекта и гайдиком по локальному запуску
- Дописать тесты, проверяющие некорректную работу программы (они как раз являются наиболее интересными и ценными)

2024-02-05 19:02 UTC, TurboGoose commented on http/ALL_HTTP_REQUESTS.http
> +
Тут и везде далее можно использовать следующие конструкции

```http request
###  get currency by code
GET http://localhost:8080/currency/USD
```


Плюсы:
+ так короче
+ при вызове метода в идее будет отображаться строка, написанная после решеток (типа имени теста) - это удобно, тк позволяет легче их различать

2024-02-05 19:02 UTC, TurboGoose commented on pom.xml
> +        </dependency>
Не используемая зависимость. Удолить

PS: эта зависимость меня запутала, тк я увидел "javax", что подразумевает tomcat <= 9, и пытался запускать на нем (в итоге не заработало). Только потом я увидел вверху jakarta, что подразумевает tomcat 10 😃

2024-02-05 19:02 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/CurrencyDao.java
> +             ResultSet resultSet = statement.executeQuery(SQL)) {
NIT: В целом ResultSet можно не засовывать в try-with-resources, тк он автоматически закрывается вместе со statement'ом

2024-02-05 19:02 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/CurrencyDao.java
> +    public Currency getCurrencyByCode(String code) throws RuntimeException {
RuntimeException не проверяемое исключение, его можно не писать в сигнатуре)

2024-02-05 19:02 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/CurrencyDao.java
> +            throw new RuntimeException();
Здесь и дальше стоит обернуть выброшенное исключение:
```java
throw new RuntimeException(e);
```

Так в логах будет отображаться, что именно пошло не так, а не просто пустой RuntimeException.

В данном случае задача RuntimeException - сделать проверяемое SQLException непроверяемым, чтобы не указывать его в сигнатурах функций и не загромождать код. Сама информация об исключении нам нужна, выкидывать ее не стоит

2024-02-05 19:02 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/CurrencyDao.java
> +            while (resultSet.next()) {
В этом методе ты ожидаешь получить 0 или 1 запись (в силу индекса unique в базе). Поэтому более уместным будет if.

Кроме того, если валюта не нашлась, уместнее кидать исключение CurrencyNotFoundException (как раз в блоке else) вместо того, чтобы возвращать пустую валюту.

Представь: пользователь вводит код не существующей валюты, а ему возвращается пустая валюта вместо ошибки 404. Контринтуитивно как-то)

Аналогичные замечания относятся к `getCurrencyById`.

2024-02-05 19:02 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/CurrencyDao.java
> +
Отлично, все случаи предусмотрены 👍

2024-02-05 19:02 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/CurrencyDao.java
> +                throw new SQLException();
По сути ведь этот случай означает, что ничего не было добавлено? Если да, то мб лучше использовать более говорящий тип исключения?

2024-02-05 19:02 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/CurrencyDao.java
> +        try (PreparedStatement preparedStatement = connection.prepareStatement("SELECT COUNT(*) FROM currencies WHERE code = ?")) {
Если везде есть отдельная переменная SQL, то и тут тоже нужно придерживаться единого стиля

2024-02-05 19:02 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/CurrencyDao.java
> +            }
Наверное можно даже просто
 ```java
return resultset.next();
```

2024-02-05 19:02 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/CurrencyExchangeDao.java
> +                }
Чтобы так не делать, следует свои кастомные исключения наследовать от RuntimeException (непроверяемые), а не от Exception (проверяемые), чтобы таким образом их каждый раз не перебрасывать

2024-02-05 19:02 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/model/ExchangeRate.java
> +    private long id;
Лучше везде использовать объекты (в данном случае Long)

2024-02-05 19:02 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/exceptions/CurrencyNotFoundException.java
> +public class CurrencyNotFoundException extends Exception {
extends RuntimeException

2024-02-05 19:02 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/ExchangeRateDao.java
> +    public List<ExchangeRate> getListOfExchangeRates() {
Лучше назвать просто getAllExchangeRates (ide и так подскажет, что ты возвращаешь list 🙂)

2024-02-05 19:02 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/ExchangeRateDao.java
> +                "INNER JOIN currencies cur2 ON exch.targetcurrencyid = cur2.id;";
NIT: Вместо \n лучше просто использовать пробелы в конце строки
А так все написано корректно👍

2024-02-05 19:02 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/ExchangeRateDao.java
> +            throw new CurrencyNotFoundException("Currency is not exists");
NIT: было бы прикольно в сообщение добавить код несуществующей валюты

2024-02-05 19:02 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/ExchangeRateDao.java
> +    public ExchangeRate addExchangeRate(String baseCurrencyCode, String targetCurrencyCode, float rate) throws DuplicateCurrencyExchangeException, CurrencyNotFoundException {
Чтобы избежать такого, мы как раз и хотим наследовать наши исключения от RuntimeException

2024-02-05 19:02 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/ExchangeRateDao.java
> +    public ExchangeRate addExchangeRate(String baseCurrencyCode, String targetCurrencyCode, float rate) throws DuplicateCurrencyExchangeException, CurrencyNotFoundException {
Как раз чтобы избежать такого, мы и хотим наследовать наши исключения от RuntimeException)

2024-02-05 19:02 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/ExchangeRateDao.java
> +            int count = resultSet.getInt(1);
Неаккуратно обработал: если next() вернет false, то получишь исключение в getInt()

2024-02-05 19:02 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/ExchangeRateDao.java
> +    public List<ExchangeRate> exchangeRateListByCurrency(String path) {
Лучше назвать getExchangeRatesByCurrency

2024-02-05 19:02 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/exceptions/DuplicateCurrencyExchangeException.java
> +public class DuplicateCurrencyExchangeException extends Exception {
Лучше бы подошло название DuplicateExchangeRateException или ExchangeRateAlreadyExistsException

2024-02-05 19:02 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/exceptions/DuplicateCurrencyExchangeException.java
> +public class DuplicateCurrencyExchangeException extends Exception {
RuntimeException

2024-02-05 19:02 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/model/CurrencyExchange.java
> +public class CurrencyExchange {
Наверное, будет логичнее назвать просто Exchange, чтобы не выбивать из общей стилистики (ты же не называешь класс CurrencyExchangeRate, а просто ExchangeRate)

2024-02-05 19:02 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/ExchangeRateDao.java
> +    public boolean isExchangeRatesExists(long baseCurrencyId, long targetCurrencyId) {
Почему rates? По одной паре же)

2024-02-05 19:02 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/CurrencyExchangeDao.java
> +        if (currencyDao.isCodeExists(baseCurrencyCode) && currencyDao.isCodeExists(targetCurrencyCode)) {
Ты сначала извлекаешь валюты, а затем проверяешь существуют ли они. Логичнее поступить наоборот

2024-02-05 19:02 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/CurrencyExchangeDao.java
> +            } else if (!exchangeRateDao.isExchangeRatesExists(baseCurrency.getId(), targetCurrency.getId())) {
Просто else

2024-02-05 19:02 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/CurrencyExchangeDao.java
> +                            if (baseRate.getBaseCurrency().getId().equals(targetRate.getBaseCurrency().getId())) {
Когда ты нашел первую такую пару, то тебе нет смысла продолжать итерироваться по циклам - надо выходить из них. Тут 2 варианта:
- в случае, если ты оставляешь циклы в текущей функции, то использовать break с меткой, чтобы выйти из вложенных циклов (никто так не делает)
- вынести код в отдельную функцию и сделать return (наиболее предпочтительный варик)

2024-02-07 09:56 UTC, KostyaDemens commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/CurrencyExchangeDao.java
> +                            if (baseRate.getBaseCurrency().getId().equals(targetRate.getBaseCurrency().getId())) {
А если я в if просто пропишу return currencyExchange? Тогда всё работает как надо. И из цикла выходит. Приемлем такой вариант?

`rate = targetRate.getRate() / baseRate.getRate();
                                currencyExchange.setBaseCurrency(baseRate.getTargetCurrency());
                                currencyExchange.setTargetCurrency(targetRate.getTargetCurrency());
                                currencyExchange.setRate(rate);
                                currencyExchange.setAmount(amount);
                                currencyExchange.setConvertedAmount(rate * amount);
                                return currencyExchange;`

2024-02-07 17:32 UTC, KostyaDemens commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/ExchangeRateDao.java
> +            throw new CurrencyNotFoundException("Currency is not exists");
Реализовал, но в сервлете ExchangeRateByCodeServlet. И кривовато, т.к пишу, что не существует одна из двух предоставленных валют. Пока не понял, как можно подставить конкретную неправильную валюту

2024-02-07 17:36 UTC, KostyaDemens commented on src/main/java/by/bsuir/kostyademens/currencyexchange/model/ExchangeRate.java
> +    private long id;
Заменил. А чем обусловлено использование Long, а не long?

2024-02-07 18:04 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/model/ExchangeRate.java
> +    private long id;
Это скорее связано с теми инструментами, что будут использоваться для работы с БД в дальнейшем.
Основной прикол в том, что значени по-умолчанию для long = 0, а для Long = null, что во втором случае позволяет менее двусмысленно понять отсутствие какого-то значения.
Вообще говоря, это вкусовщина, но мне кажется, что так лучше)

2024-02-07 18:06 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/CurrencyExchangeDao.java
> +                            if (baseRate.getBaseCurrency().getId().equals(targetRate.getBaseCurrency().getId())) {
Да, в этом случае это уместно, но в более общем случае актуально сказанное выше. (А так я бы вобще в функцию вынес)

2024-02-10 11:06 UTC, TurboGoose commented on http/ALL_HTTP_REQUESTS.http
> +### exchange rate is not found bc currency is not exists (expected: 500)
400?

2024-02-10 13:12 UTC, TurboGoose requested changes
В целом код стал намного чище - глаз радуется  🙂

Из замечаний и улучшений:
- Когда я говорил про вынесение json сериализации в отдельный класс, я немного не это имел в виду) Надо было сделать класс, наследующийся от HttpServlet (назвать его например JsonServlet), от которого бы наследовались все сервлеты нашего приложения и положить эти методы туда. Туда же можно запихнуть и обработку PATCH метода
- Стоило бы еще реализовать пару исключений для полного логического набора из пар Duplidated/NotFound + Currency/ExchangeRate + Exception
- Еще ты забыл применить те замечания, что я тебе указывал в CurrencyDao, для  ExchangeRateDao.java - посмотри на последний повнимательней 🙂
- Еще следует написать более корректную логику для обраобтки ошибки дублирующей вставки (напишу в чате)

2024-02-10 13:12 UTC, TurboGoose commented on pom.xml
> +        </dependency>
тесты на junit мы пока все равно не пишем, так что удаляем эти штуки

2024-02-10 13:12 UTC, TurboGoose commented on pom.xml
> +        </dependency>
Если мы теперь используем gson, то это удаляем - нечего лишние зависимости таскать)

2024-02-10 13:12 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/CurrencyDao.java
> +            }
Все-таки решил оставить? Почему?

2024-02-10 13:12 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/CurrencyDao.java
> +                throw new SQLException();
Исключение с таким названием слишком низкоуровневое, тк оно раскрывает детали реализации dao слоя, а бизнес слой в идеале не должен об этом знать

2024-02-10 13:12 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/CurrencyDao.java
> +                currency.setName(resultSet.getString("fullName"));
NIT: если используются сеттеры, то лучше удалить конструктор со всеми аргументами в Currency, раз уж он не используется

2024-02-10 13:12 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/ExchangeRateDao.java
> +            }
Аналогично тому замечанию про if и throw в else, что было в CurrencyDao. Также для полного набора исключений не помешало бы  ExchangeRateNotFoundException)

2024-02-10 13:12 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/ExchangeRateDao.java
> +
Я думал это affectedRows)

2024-02-10 13:12 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/ExchangeRateDao.java
> +            }
Не обработан отрицательный случай (по аналогии с CurrenciesDao)

2024-02-10 13:12 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/ExchangeRateDao.java
> +        List<ExchangeRate> exchangeRates = new ArrayList<>();
Лучше объявлять переменную поближе к месту использования

2024-02-10 13:12 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/controller/ExchangeRateByCodeServlet.java
> +            System.out.println(e.getMessage());
Лучше e.printStackTrace(). (В остальных местах тоже)

2024-02-10 13:12 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/controller/ExchangeRateByCodeServlet.java
> +            throw new RuntimeException(e);
Зачем дальше пробрасывать?
Можно же сказать об этом пользователю и залогировать, как ты делал это выше

2024-02-10 13:12 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/controller/ExchangeRateByCodeServlet.java
> +            sendError(resp, 500, "Валюта с кодом: " + path.substring(0, 3) + " или с кодом: " + path.substring(3, 6) + " не существует");
5xx- это внутренние ошибки сервера, на которые пользователь не влияет. Допустим, база упала. Тут именно пользователь виноват, что ввел неправильные данные, поэтому мы должны возвратить ему код 4xx. Какой - реши сам (погугли их семантику)

2024-02-10 13:12 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/controller/ExchangeRateByCodeServlet.java
> +    }
Следует сделать базовый класс для всех сервлетов, используемых в нашем приоложении, который, в свою очередь, будет наследоваться от HttpServlet и вынести этот метод туда

2024-02-10 13:12 UTC, TurboGoose commented on .gitignore
> +.idea/*
Саму папку .idea гит так не заигнорит - вместо всех этих записей, начинающихся на ".idea..." надо вставить просто ".idea")

2024-02-10 13:18 UTC, KostyaDemens commented on .gitignore
> +.idea/*
Разве не заигнорит? Сейчас же на гитхабе не отображается данная папка в ветке dev

2024-02-17 17:44 UTC, TurboGoose requested changes
Шаг за шагом приближаемся к идеалу) Контроллеры выглядят почти эталонно, dao и сервисный слои тоже по бОльшей части уже готовы, в некоторых местах только аккуратно предусмотреть недостающие случаи. В остальных местах ошибки в основном по невнимательности - иногда забываешь про то, какие подходы используешь в других классах, из-за чего делаешь лишние приседания)) Пожалуйста, будь повнимательней - мне тоже тяжеловато отлавливать такие ошибки 🙂

2024-02-17 17:44 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/controller/CurrencyExchangeServlet.java
> +            }
Здесь по-идее из сервиса должно кидаться ExchangeRateNotFoundException вместо null и ловиться в catch. Иначе выходит, что наше кастомное исключение не используется

2024-02-17 17:44 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/controller/ExchangeRateByCodeServlet.java
> +        String path = req.getPathInfo().substring(1);
А проверить path на пустоту как в методе выше?

2024-02-17 17:44 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/controller/ExchangeRateByCodeServlet.java
> +            ExchangeRate exchangeRate = exchangeRateService.changeExchangeRate(path, new BigDecimal(rate));
По-хорошему rate тоже проверить, тк если передать "ahsdflhasd", то будет NumberFormatException (в других местах тоже)

2024-02-17 17:44 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/controller/JSONServlet.java
> +    }
Я бы написал универсальный метод с сигнатурой
```java
private void send(HttpServletResponse resp, int errorCode, Object obj) throws IOException
```
и переиспользовал его в sendResponse и sendError.
Причем sendResponse сделал бы в двух версиях: со статусом возврата  в аргументах (для случаев, если надо передать код 2хх или 3xx отличный от 200) и без (по-умолчанию 200)

2024-02-17 17:44 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/controller/JSONServlet.java
> +                break;
Зачем это переопределять, в service же и так все написано?)
Еще аргументы против этого решения:
- Для метода get в service есть дополнительная логика, которую ты не перенес
- Правило, что если post, то всегда 201 слишком грубое. В данном проекте оно так, но в общем случае так не надо делать

Я бы остановился на том варианте, что я предлагал, ведь в данном случае нас интересует только post, остальное отдаем на откуп дефолтному поведению

2024-02-17 17:44 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/CurrencyDao.java
> +                throw new NoRowsAffectedException("No rows where affected by the update operation.");
Наверное действительно лучше кинуть SQLException, а это исключение удалить в принципе как класс.

В прошлый раз я забраковал такой подход, тк подумал, что именно это означает, что в нашей БД уже существует такая валюта. Однако сейчас я понимаю, что исключение вылетит еще на `int affectedRows = statement.executeUpdate();`, и до этой строчки дело просто не дойдет.

2024-02-17 17:44 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/CurrencyDao.java
> +        Currency currency = new Currency();
NIT: здесь и в других местах я бы перенес инициализацию переменной и ее return ближе к месту заполнения данными (в данном случае после строки `if (generatedKeys.next()) {`, где дальше используются сеттеры). Так просто читать полегче - не надо глазами скакать)

2024-02-17 17:44 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/CurrencyDao.java
> +            }
А если не 19? Тогда мы выходим из метода будто все хорошо, но это, очевидно, не так

2024-02-17 17:44 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/ExchangeRateDao.java
> +        String targetCurrencyCode = path.substring(3, 6);
Этот разбор входящих параметров должен происходить в контроллере. В сервис и далее следует передавать разделенные коды двух валют

2024-02-17 17:44 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/ExchangeRateDao.java
> +        CurrencyDao currencyDao = new CurrencyDao();
Лучше вынести в переменную класса и дальше везде использовать ее

2024-02-17 17:44 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/ExchangeRateDao.java
> +        }
У тебя же и так кидается это исключение в `getCurrencyByCode`.

2024-02-17 17:44 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/ExchangeRateDao.java
> +            throw new CurrencyNotFoundException("Currency is not exists");
Аналогично тому, что выше про `getCurrencyByCode`

2024-02-17 17:44 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/ExchangeRateDao.java
> +        }
У тебя же есть проверка на код 19 ниже. Проверку уникальности лучше поручить механизмам базы, а этот блок кода убрать

2024-02-17 17:44 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/ExchangeRateDao.java
> +        try (PreparedStatement preparedStatement = connection.prepareStatement("SELECT COUNT(*) FROM exchangeRates WHERE baseCurrencyId = ? AND targetCurrencyId = ?")) {
NIT:

Лучше вынести в отдельную переменную, чтобы везде был общий стиль.

И зачем count(*)? У тебя же индекс unique стоит на пару (baseCurrencyId, baseCurrencyId). То есть там либо 0, либо 1.

Я бы сделал так:
```sql
SELECT * FROM exchangeRates WHERE baseCurrencyId = ? AND targetCurrencyId = ?
```

и в конце 

```java
return resultSet.next();
```

Последнее изменение я предлагал и раньше, но оно не сработало, тк я проглядел count, а он всегда возвращает значение, соответственно в таком случае всегда возвращалось true.

2024-02-17 17:44 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/ExchangeRateDao.java
> +            throw new RuntimeException();
Забыл передать e (в других местах в этом классе тоже)

2024-02-17 17:44 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dto/CurrencyDto.java
> +    }
Если других конструкторов в классе нет, то этот и так неявно создастся, те его можно убрать. Ну или добавить конструктор со всеми параметрами

2024-02-17 17:44 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dto/ExchangeDto.java
> +    private Currency baseCurrency;
В dto клссах должны использоваться поля с dto типами соответствующих моделей, те в данном случае CurrencyDto (в других местах аналогично)

2024-02-17 17:44 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/filter/ResponseFilter.java
> +    public void init(FilterConfig config) throws ServletException {}
NIT: методы init и destroy точно так же реализованы по-умолчанию в Filter. Можно их не переопределять лишний раз

2024-02-17 17:44 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/filter/ResponseFilter.java
> +        req.setCharacterEncoding("UTF-8");
Наоборот, мы хотим знать в какой кодировке пришел запрос. А так мы его просто так перезатираем) Следует убрать

2024-02-17 17:44 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/filter/ResponseFilter.java
> +        resp.setContentType("application/json");
NIT: что-то устанавливать в response лучше на обратном пути из контроллера, те после chain.doFilter

2024-02-17 17:44 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/mapper/ModelMapper.java
> +        exchangeRateDto.setTargetCurrency(exchangeRate.getTargetCurrency());
Модели валют надо тоже сконвертировать в дто

2024-02-17 17:44 UTC, TurboGoose commented on pom.xml
> +        <junit.version>5.9.2</junit.version>
Убери этот пропс, он же не используется)

2024-02-17 17:44 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/service/CurrencyExchangeService.java
> +    public ExchangeRate exchangeRate = new ExchangeRate();
Поч public?)

2024-02-17 17:44 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/service/CurrencyExchangeService.java
> +        targetCurrency = currencyDao.getCurrencyByCode(targetCurrencyCode);
Зачем, у тебя же уже лежат валюты в этих переменных - ты их присвоил еще в методе chooseCurrencyConversionRate

2024-02-17 17:44 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/service/CurrencyExchangeService.java
> +        targetCurrency = currencyDao.getCurrencyByCode(targetCurrencyCode);
Зачем, у тебя же уже лежат валюты в этих переменных - ты их присвоил еще в методе chooseCurrencyConversionRate

2024-02-17 17:44 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/service/CurrencyExchangeService.java
> +    public ExchangeDto exchangeDto = new ExchangeDto();
Лучше убрать эту переменную и возвращать из методов свежий экземпляр

2024-02-17 17:44 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/service/CurrencyExchangeService.java
> +    public Currency targetCurrency;
Переменные с состоянием лучше не хранить в классах-сервисах, тк это чревато гонками за данными, в многопользовательских приложениях. Лучше создавать их в методах и передавать через аргументы.

2024-02-17 17:44 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/service/CurrencyExchangeService.java
> +    public ExchangeDto crossRate(String baseCurrencyCode, String targetCurrencyCode, BigDecimal amount) {
Тогда метод лучше назвать по аналогии - crossExchangeRate

2024-02-17 17:44 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/service/CurrencyExchangeService.java
> +    public ExchangeDto chooseCurrencyConversionRate(String baseCurrencyCode, String targetCurrencyCode, BigDecimal amount) {
Все методы кроме этого следует сделать private, тк это детали внутренней реализации, которые не предполагается использовать вне класса

2024-02-18 13:18 UTC, KostyaDemens commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/CurrencyDao.java
> +                throw new NoRowsAffectedException("No rows where affected by the update operation.");
В таком случае наверное вообще имеет смысл удалить этот блок и ничего в нем не прокидывать. 

Если я сделаю строку statement.executeUpdate - у меня сразу перехватывается исключение

2024-02-18 13:43 UTC, KostyaDemens commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/CurrencyDao.java
> +        Currency currency = new Currency();
Реализовал в местах, где это было возможно
Вообще я мог бы просунуть инициализацию переменных вплотную к setтерам везде, но тогда в некоторых местах получался бы вот такой код:

`if (resultSet.next()) {
            long id = resultSet.getLong("id");
            String currencyCode = resultSet.getString("code");
            String sign = resultSet.getString("sign");
            String fullName = resultSet.getString("fullName");

            Currency currency = new Currency(id, currencyCode, sign, fullName);
            return currency;`
            
Что сильно выбивается из общей стилистики класса. Потому в некоторых местах оставил как было, а в остальных сделал как ты сказал

2024-02-19 05:46 UTC, KostyaDemens commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/CurrencyDao.java
> +                throw new NoRowsAffectedException("No rows where affected by the update operation.");
Раз исключение будет выбиваться еще на моменте выполнения запроса (execute.update). Может имеет смысл вообще убрать этот блок if и переменную affectedRows, а оставить statement.executeUpdate

2024-02-19 10:41 UTC, KostyaDemens commented on src/main/java/by/bsuir/kostyademens/currencyexchange/filter/ResponseFilter.java
> +        resp.setContentType("application/json");
Попробовал. Не пашет :( 
Не возвращается кодировка и contentType не устанавливается в таком случае

2024-02-24 18:07 UTC, TurboGoose requested changes
Супер!
Вопросов все меньше и меньше - в этот раз написал лишь пару мелких придирок. Исправляешь их, я принимаю ПР, а дальше деплоишь на удаленный сервер.

2024-02-24 18:07 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/controller/CurrencyExchangeServlet.java
> +            } else if (!amount.matches("\\d+")) {
По такой логике дробный amount типа 2.45 не сработает из-за точки

2024-02-24 18:07 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/controller/CurrencyByCodeServlet.java
> +        String path = req.getPathInfo().substring(1);
Лучше назвать code, раз по сути переменная таковым и является (в других местах тоже такое встречается)

2024-02-24 18:07 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/controller/CurrencyExchangeServlet.java
> +            ExchangeDto exchangeDto = currencyExchangeService.chooseCurrencyConversionRate(baseCurrencyCode, targetCurrencyCode, BigDecimal.valueOf(Long.parseLong(amount)));
Лучше как-то переименовать - тут же ты не просто выбираешь, а еще делаешь конвертацию)

2024-02-24 18:07 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/controller/ExchangeRateByCodeServlet.java
> +            } else if (rate == null) {
В подобный случаях, когда в блоке if есть return, можно дальше использовать не else if, а просто следующий блок if - семантически то же самое получается. Как по мне это более лаконично выглядит, но это чистая вкусовщина. Ничего исправлять не надо, просто вброс альтернативного варианта)

2024-02-24 18:07 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/controller/CurrencyExchangeServlet.java
> +            ExchangeDto exchangeDto = currencyExchangeService.chooseCurrencyConversionRate(baseCurrencyCode, targetCurrencyCode, BigDecimal.valueOf(Long.parseLong(amount)));
Можно просто использовать конструктор BigDecimal

2024-02-24 18:07 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/controller/JSONServlet.java
> +    private static final int DEFAULT_SUCCESS_STATUS = 200;
Вынес константу - лайк

2024-02-24 18:07 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/ExchangeRateDao.java
> +        CurrencyDao currencyDao = new CurrencyDao();
Лучше вынести в переменную класса и использовать ее во всех методах

2024-02-24 18:07 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/dao/ExchangeRateDao.java
> +    public ExchangeRate changeExchangeRate(String baseCurrencyCode, String targetCurrencyCode, BigDecimal rate) throws CurrencyNotFoundException {
Лишнее

2024-02-24 18:07 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/service/CurrencyExchangeService.java
> +    private ExchangeDto mapValuesToCurrency(String baseCurrencyCode, String targetCurrencyCode, BigDecimal amount, String path) {
Алярм! Неиспользуемая переменная в аргументах

2024-02-24 18:07 UTC, TurboGoose commented on src/main/java/by/bsuir/kostyademens/currencyexchange/service/CurrencyExchangeService.java
> +        }
Обрати внимание на названия методов - в них должен быть глагол

2024-02-24 18:07 UTC, TurboGoose commented on pom.xml
> +    <name>exchangeDto</name>
Рефакторинг дал сбой))))
За идеей надо иногда следить и подтирать

2024-03-03 20:31 UTC, TurboGoose approved these changes

2024-03-03 20:31 UTC, merged